
package view;

/**
 * Frame para criação de uma janela com informações sobre o sistema.
 * @author Guilherme Souto Cardoso
 * @since Classe criada em: 18/09/2017
 */

public class FrameSobre extends javax.swing.JFrame {

    /**
     * Creates new form FrameSobre
     */
    public FrameSobre() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSobre = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSobre = new javax.swing.JTextArea();
        btFecharSobre = new javax.swing.JButton();
        lbIconSobre = new javax.swing.JLabel();
        lbDutyCallsSobre = new javax.swing.JLabel();
        lbTituloSobre1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informações do Sistema");

        panelSobre.setBackground(new java.awt.Color(0, 102, 51));

        taSobre.setEditable(false);
        taSobre.setColumns(20);
        taSobre.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        taSobre.setRows(5);
        taSobre.setText("\nFATEC IPIRANGA\nALUNO: GUILHERME SOUTO CARDOSO\nANÁLISE & DESENVOLVIMENTO DE SISTEMAS\n4º SEMESTRE - TARDE\nPROGRAMAÇÃO AVANÇADA ORIENTADA A OBJETOS\nPROF. ALEXANDRE CASSIANO\nVERSÃO: 1.2");
        jScrollPane1.setViewportView(taSobre);

        btFecharSobre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btFecharSobre.setText("Fechar");
        btFecharSobre.setAlignmentY(0.0F);
        btFecharSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFecharSobre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFecharSobre.setMaximumSize(new java.awt.Dimension(70, 30));
        btFecharSobre.setMinimumSize(new java.awt.Dimension(70, 30));
        btFecharSobre.setPreferredSize(new java.awt.Dimension(70, 30));
        btFecharSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharSobreActionPerformed(evt);
            }
        });

        lbIconSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon.png"))); // NOI18N

        lbDutyCallsSobre.setFont(new java.awt.Font("Perpetua Titling MT", 3, 36)); // NOI18N
        lbDutyCallsSobre.setForeground(new java.awt.Color(255, 255, 0));
        lbDutyCallsSobre.setText("Duty Calls");

        lbTituloSobre1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTituloSobre1.setForeground(new java.awt.Color(255, 255, 255));
        lbTituloSobre1.setText("Sistema de Atribuição de Tarefas do Exército");

        javax.swing.GroupLayout panelSobreLayout = new javax.swing.GroupLayout(panelSobre);
        panelSobre.setLayout(panelSobreLayout);
        panelSobreLayout.setHorizontalGroup(
            panelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSobreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelSobreLayout.createSequentialGroup()
                        .addGroup(panelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelSobreLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbIconSobre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbDutyCallsSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbTituloSobre1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelSobreLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(btFecharSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSobreLayout.setVerticalGroup(
            panelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSobreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloSobre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDutyCallsSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbIconSobre, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btFecharSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSobre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharSobreActionPerformed
        dispose();
    }//GEN-LAST:event_btFecharSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameSobre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFecharSobre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDutyCallsSobre;
    private javax.swing.JLabel lbIconSobre;
    private javax.swing.JLabel lbTituloSobre1;
    private javax.swing.JPanel panelSobre;
    private javax.swing.JTextArea taSobre;
    // End of variables declaration//GEN-END:variables
}
