
package view;

import controller.BuscaAdvertencia;
import controller.BuscaAtividade;
import controller.BuscaSoldado;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 * Frame para criação de um menu para a aplicação.
 * @author Guilherme Souto Cardoso
 * @since Classe criada em: 18/09/2017
 */

public class FrameMenu extends javax.swing.JFrame {
    
    /**
     * Creates new form FrameMenu
     */
    public FrameMenu() {
        setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbImagemMenu = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        itemCadastrarSoldadoMenuCadastro = new javax.swing.JMenuItem();
        itemCadastrarAtividadesMenuCadastro = new javax.swing.JMenuItem();
        itemAlterarDadosSoldadoMenuCadstro = new javax.swing.JMenuItem();
        itemAdvertenciasMenuCadstro = new javax.swing.JMenuItem();
        menuListagens = new javax.swing.JMenu();
        itemListaSoldadosMenuListagens = new javax.swing.JMenuItem();
        itemListaAtividadesMenuListagens = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        itemTodosSoldadosMenuRelatorios = new javax.swing.JMenuItem();
        itemIdadeAlturaMenuRelatorios = new javax.swing.JMenuItem();
        itemRecrutadosEsteAnoMenuRelatorios = new javax.swing.JMenuItem();
        itemPraticaTiroMenuRelatorios = new javax.swing.JMenuItem();
        itemAdvertenciasMenuRelatorios = new javax.swing.JMenuItem();
        itemRelatorioGeralMenuRelatorios = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        itemSobreMenuSair = new javax.swing.JMenuItem();
        itemSairMenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Atribuição de Tarefas do Exército");

        lbImagemMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/texture.jpg"))); // NOI18N

        menuCadastro.setText("Cadastro");
        menuCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCadastro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuCadastro.setMargin(new java.awt.Insets(0, 6, 0, 6));

        itemCadastrarSoldadoMenuCadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemCadastrarSoldadoMenuCadastro.setText("Cadastrar Soldado");
        itemCadastrarSoldadoMenuCadastro.setToolTipText("Cadastrar um novo soldado no sistema");
        itemCadastrarSoldadoMenuCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemCadastrarSoldadoMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarSoldadoMenuCadastroActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCadastrarSoldadoMenuCadastro);

        itemCadastrarAtividadesMenuCadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemCadastrarAtividadesMenuCadastro.setText("Cadastrar Atividades");
        itemCadastrarAtividadesMenuCadastro.setToolTipText("Cadastrar uma atividade para um soldado cadastrado no sistema");
        itemCadastrarAtividadesMenuCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemCadastrarAtividadesMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarAtividadesMenuCadastroActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCadastrarAtividadesMenuCadastro);

        itemAlterarDadosSoldadoMenuCadstro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemAlterarDadosSoldadoMenuCadstro.setText("Alterar Dados do Soldado");
        itemAlterarDadosSoldadoMenuCadstro.setToolTipText("Alterar ou excluir dados de um soldado cadastrado no sistema");
        itemAlterarDadosSoldadoMenuCadstro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemAlterarDadosSoldadoMenuCadstro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAlterarDadosSoldadoMenuCadstroActionPerformed(evt);
            }
        });
        menuCadastro.add(itemAlterarDadosSoldadoMenuCadstro);

        itemAdvertenciasMenuCadstro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemAdvertenciasMenuCadstro.setText("Advertências");
        itemAdvertenciasMenuCadstro.setToolTipText("Mostrar a quantidade de advertências de um soldado e sua situação");
        itemAdvertenciasMenuCadstro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemAdvertenciasMenuCadstro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAdvertenciasMenuCadstroActionPerformed(evt);
            }
        });
        menuCadastro.add(itemAdvertenciasMenuCadstro);

        jMenuBar1.add(menuCadastro);

        menuListagens.setText("Listagens");
        menuListagens.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuListagens.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuListagens.setMargin(new java.awt.Insets(0, 6, 0, 6));

        itemListaSoldadosMenuListagens.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemListaSoldadosMenuListagens.setText("Lista de Soldados");
        itemListaSoldadosMenuListagens.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemListaSoldadosMenuListagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListaSoldadosMenuListagensActionPerformed(evt);
            }
        });
        menuListagens.add(itemListaSoldadosMenuListagens);

        itemListaAtividadesMenuListagens.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemListaAtividadesMenuListagens.setText("Lista de Atividades");
        itemListaAtividadesMenuListagens.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemListaAtividadesMenuListagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListaAtividadesMenuListagensActionPerformed(evt);
            }
        });
        menuListagens.add(itemListaAtividadesMenuListagens);

        jMenuBar1.add(menuListagens);

        menuRelatorios.setText("Relatórios");
        menuRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuRelatorios.setMargin(new java.awt.Insets(0, 6, 0, 6));

        itemTodosSoldadosMenuRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemTodosSoldadosMenuRelatorios.setText("Todos os Soldados");
        itemTodosSoldadosMenuRelatorios.setToolTipText("Relatório com o nome de todos os soldados cadastrados no sistema por caserna");
        itemTodosSoldadosMenuRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemTodosSoldadosMenuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTodosSoldadosMenuRelatoriosActionPerformed(evt);
            }
        });
        menuRelatorios.add(itemTodosSoldadosMenuRelatorios);

        itemIdadeAlturaMenuRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemIdadeAlturaMenuRelatorios.setText("Idade & Altura");
        itemIdadeAlturaMenuRelatorios.setToolTipText("Relatório de todos os soldados cadastrados no sistema mostrando idade e altura");
        itemIdadeAlturaMenuRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemIdadeAlturaMenuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIdadeAlturaMenuRelatoriosActionPerformed(evt);
            }
        });
        menuRelatorios.add(itemIdadeAlturaMenuRelatorios);

        itemRecrutadosEsteAnoMenuRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemRecrutadosEsteAnoMenuRelatorios.setText("Recrutados este ano");
        itemRecrutadosEsteAnoMenuRelatorios.setToolTipText("Relatório com os nomes dos soldados que foram recrutados este ano");
        itemRecrutadosEsteAnoMenuRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemRecrutadosEsteAnoMenuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRecrutadosEsteAnoMenuRelatoriosActionPerformed(evt);
            }
        });
        menuRelatorios.add(itemRecrutadosEsteAnoMenuRelatorios);

        itemPraticaTiroMenuRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemPraticaTiroMenuRelatorios.setText("Prática de tiro");
        itemPraticaTiroMenuRelatorios.setToolTipText("Relatório com as presenças na atividade mensal de prática de tiro");
        itemPraticaTiroMenuRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemPraticaTiroMenuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPraticaTiroMenuRelatoriosActionPerformed(evt);
            }
        });
        menuRelatorios.add(itemPraticaTiroMenuRelatorios);

        itemAdvertenciasMenuRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemAdvertenciasMenuRelatorios.setText("Advertências");
        itemAdvertenciasMenuRelatorios.setToolTipText("Relatório com os nomes dos soldados que receberam mais advertências");
        itemAdvertenciasMenuRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemAdvertenciasMenuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAdvertenciasMenuRelatoriosActionPerformed(evt);
            }
        });
        menuRelatorios.add(itemAdvertenciasMenuRelatorios);

        itemRelatorioGeralMenuRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemRelatorioGeralMenuRelatorios.setText("Relatório Geral");
        itemRelatorioGeralMenuRelatorios.setToolTipText("Relatório com os dados de todos os soldados cadastrados no sistema");
        itemRelatorioGeralMenuRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemRelatorioGeralMenuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRelatorioGeralMenuRelatoriosActionPerformed(evt);
            }
        });
        menuRelatorios.add(itemRelatorioGeralMenuRelatorios);

        jMenuBar1.add(menuRelatorios);

        menuSair.setText("Sair");
        menuSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuSair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuSair.setMargin(new java.awt.Insets(0, 6, 0, 6));

        itemSobreMenuSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemSobreMenuSair.setText("Sobre");
        itemSobreMenuSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemSobreMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSobreMenuSairActionPerformed(evt);
            }
        });
        menuSair.add(itemSobreMenuSair);

        itemSairMenuSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemSairMenuSair.setText("Sair");
        itemSairMenuSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemSairMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairMenuSairActionPerformed(evt);
            }
        });
        menuSair.add(itemSairMenuSair);

        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImagemMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImagemMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSairMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairMenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemSairMenuSairActionPerformed

    private void itemSobreMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSobreMenuSairActionPerformed
        FrameSobre frameSobre = new FrameSobre();
        frameSobre.setVisible(true);
    }//GEN-LAST:event_itemSobreMenuSairActionPerformed

    private void itemCadastrarSoldadoMenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarSoldadoMenuCadastroActionPerformed
        FrameSoldado frameSoldado = new FrameSoldado();
        frameSoldado.setVisible(true);
    }//GEN-LAST:event_itemCadastrarSoldadoMenuCadastroActionPerformed

    private void itemCadastrarAtividadesMenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarAtividadesMenuCadastroActionPerformed
        FrameAtividade frameAtividade = new FrameAtividade();
        frameAtividade.setVisible(true);
    }//GEN-LAST:event_itemCadastrarAtividadesMenuCadastroActionPerformed

    private void itemAlterarDadosSoldadoMenuCadstroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAlterarDadosSoldadoMenuCadstroActionPerformed
        FrameAlteraSoldado frameAlteraSoldado = new FrameAlteraSoldado();
        frameAlteraSoldado.setVisible(true);
    }//GEN-LAST:event_itemAlterarDadosSoldadoMenuCadstroActionPerformed

    private void itemListaSoldadosMenuListagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListaSoldadosMenuListagensActionPerformed
        String listagem = new String();
        try {
            BuscaSoldado.localizarTodosSoldados(listagem);
        } catch (SQLException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemListaSoldadosMenuListagensActionPerformed

    private void itemListaAtividadesMenuListagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListaAtividadesMenuListagensActionPerformed
        String listagem = new String();
        try {
            BuscaAtividade.localizarTodasAtividades(listagem);
        } catch (SQLException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemListaAtividadesMenuListagensActionPerformed

    private void itemAdvertenciasMenuCadstroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAdvertenciasMenuCadstroActionPerformed
        FrameAdvertencia frameAdvertencia = new FrameAdvertencia();
        frameAdvertencia.setVisible(true);
    }//GEN-LAST:event_itemAdvertenciasMenuCadstroActionPerformed

    private void itemTodosSoldadosMenuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTodosSoldadosMenuRelatoriosActionPerformed
        try {
            ResultSet rs = BuscaSoldado.listarTodosSoldadosRelatorio();
            JRResultSetDataSource jrRS = new JRResultSetDataSource(rs);
            JasperReport relatorioSoldados = JasperCompileManager.compileReport("C:\\Users\\San\\Documents\\NetBeans Projects\\Exercito\\src\\relatorios\\MyReports\\TodosSoldados.jrxml");
            JasperPrint impressao = JasperFillManager.fillReport(relatorioSoldados, null, jrRS);
            JasperViewer jrViewer = new JasperViewer(impressao, false);
            jrViewer.setVisible(true);
            jrViewer.toFront();
            jrViewer.setExtendedState(MAXIMIZED_BOTH);
        } catch (SQLException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemTodosSoldadosMenuRelatoriosActionPerformed

    private void itemIdadeAlturaMenuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIdadeAlturaMenuRelatoriosActionPerformed
        try {
            ResultSet rs = BuscaSoldado.listarSoldadosIdadeAltura();
            JRResultSetDataSource jrRS = new JRResultSetDataSource(rs);
            JasperReport relatorioSoldados = JasperCompileManager.compileReport("C:\\Users\\San\\Documents\\NetBeans Projects\\Exercito\\src\\relatorios\\MyReports\\SoldadosIdadeAltura.jrxml");
            JasperPrint impressao = JasperFillManager.fillReport(relatorioSoldados, null, jrRS);
            JasperViewer jrViewer = new JasperViewer(impressao, false);
            jrViewer.setVisible(true);
            jrViewer.toFront();
            jrViewer.setExtendedState(MAXIMIZED_BOTH);
        } catch (SQLException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemIdadeAlturaMenuRelatoriosActionPerformed

    private void itemRecrutadosEsteAnoMenuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRecrutadosEsteAnoMenuRelatoriosActionPerformed
        try {
            ResultSet rs = BuscaSoldado.listarSoldadosRecrutadosEsteAno();
            JRResultSetDataSource jrRS = new JRResultSetDataSource(rs);
            JasperReport relatorioSoldados = JasperCompileManager.compileReport("C:\\Users\\San\\Documents\\NetBeans Projects\\Exercito\\src\\relatorios\\MyReports\\SoldadosRecrutadosEsteAno.jrxml");
            JasperPrint impressao = JasperFillManager.fillReport(relatorioSoldados, null, jrRS);
            JasperViewer jrViewer = new JasperViewer(impressao, false);
            jrViewer.setVisible(true);
            jrViewer.toFront();
            jrViewer.setExtendedState(MAXIMIZED_BOTH);
        } catch (SQLException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemRecrutadosEsteAnoMenuRelatoriosActionPerformed

    private void itemPraticaTiroMenuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPraticaTiroMenuRelatoriosActionPerformed
        try {
            ResultSet rs = BuscaAtividade.localizarPraticaTiro();
            JRResultSetDataSource jrRS = new JRResultSetDataSource(rs);
            JasperReport relatorioSoldados = JasperCompileManager.compileReport("C:\\Users\\San\\Documents\\NetBeans Projects\\Exercito\\src\\relatorios\\MyReports\\PraticaTiro.jrxml");
            JasperPrint impressao = JasperFillManager.fillReport(relatorioSoldados, null, jrRS);
            JasperViewer jrViewer = new JasperViewer(impressao, false);
            jrViewer.setVisible(true);
            jrViewer.toFront();
            jrViewer.setExtendedState(MAXIMIZED_BOTH);
        } catch (SQLException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemPraticaTiroMenuRelatoriosActionPerformed

    private void itemAdvertenciasMenuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAdvertenciasMenuRelatoriosActionPerformed
        try {
            ResultSet rs = BuscaAdvertencia.localizarTodasAdvertencias();
            JRResultSetDataSource jrRS = new JRResultSetDataSource(rs);
            JasperReport relatorioSoldados = JasperCompileManager.compileReport("C:\\Users\\San\\Documents\\NetBeans Projects\\Exercito\\src\\relatorios\\MyReports\\TodasAdvertencias.jrxml");
            JasperPrint impressao = JasperFillManager.fillReport(relatorioSoldados, null, jrRS);
            JasperViewer jrViewer = new JasperViewer(impressao, false);
            jrViewer.setVisible(true);
            jrViewer.toFront();
            jrViewer.setExtendedState(MAXIMIZED_BOTH);
        } catch (SQLException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemAdvertenciasMenuRelatoriosActionPerformed

    private void itemRelatorioGeralMenuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRelatorioGeralMenuRelatoriosActionPerformed
        try {
            ResultSet rs = BuscaSoldado.listarTodosSoldadosGeral();
            JRResultSetDataSource jrRS = new JRResultSetDataSource(rs);
            JasperReport relatorioSoldados = JasperCompileManager.compileReport("C:\\Users\\San\\Documents\\NetBeans Projects\\Exercito\\src\\relatorios\\MyReports\\Geral.jrxml");
            JasperPrint impressao = JasperFillManager.fillReport(relatorioSoldados, null, jrRS);
            JasperViewer jrViewer = new JasperViewer(impressao, false);
            jrViewer.setVisible(true);
            jrViewer.toFront();
            jrViewer.setExtendedState(MAXIMIZED_BOTH);
        } catch (SQLException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemRelatorioGeralMenuRelatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAdvertenciasMenuCadstro;
    private javax.swing.JMenuItem itemAdvertenciasMenuRelatorios;
    private javax.swing.JMenuItem itemAlterarDadosSoldadoMenuCadstro;
    private javax.swing.JMenuItem itemCadastrarAtividadesMenuCadastro;
    private javax.swing.JMenuItem itemCadastrarSoldadoMenuCadastro;
    private javax.swing.JMenuItem itemIdadeAlturaMenuRelatorios;
    private javax.swing.JMenuItem itemListaAtividadesMenuListagens;
    private javax.swing.JMenuItem itemListaSoldadosMenuListagens;
    private javax.swing.JMenuItem itemPraticaTiroMenuRelatorios;
    private javax.swing.JMenuItem itemRecrutadosEsteAnoMenuRelatorios;
    private javax.swing.JMenuItem itemRelatorioGeralMenuRelatorios;
    private javax.swing.JMenuItem itemSairMenuSair;
    private javax.swing.JMenuItem itemSobreMenuSair;
    private javax.swing.JMenuItem itemTodosSoldadosMenuRelatorios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbImagemMenu;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuListagens;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
