
package view;

import controller.BuscaAtividade;
import controller.GravaAtividade;
import model.Atividade;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Frame para coletar dados das Atividades.
 * @author Guilherme Souto Cardoso
 * @since Classe criada em: 19/09/2017
 */

public class FrameAtividade extends javax.swing.JFrame {
    
    /**
     * Creates new form FrameAtividade
     */
    public FrameAtividade() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAtividade = new javax.swing.JPanel();
        lbIconAtividade = new javax.swing.JLabel();
        lbDutyCallsAtividade = new javax.swing.JLabel();
        btVoltarAtividade = new javax.swing.JButton();
        lbCodigoSoldadoAtividade = new javax.swing.JLabel();
        lbNomeSoldadoAtividade = new javax.swing.JLabel();
        lbCasernaSoldadoAtividade = new javax.swing.JLabel();
        lbCodigoAtividade = new javax.swing.JLabel();
        lbMes = new javax.swing.JLabel();
        ftfCodigoSoldadoAtividade = new javax.swing.JFormattedTextField();
        tfNomeSoldadoAtividade = new javax.swing.JTextField();
        tfCasernaSoldadoAtividade = new javax.swing.JTextField();
        ftfCodigoAtividade = new javax.swing.JFormattedTextField();
        cbMes = new javax.swing.JComboBox<>();
        chkAulasTeoricas = new javax.swing.JCheckBox();
        chkCorrida = new javax.swing.JCheckBox();
        chkFlexoes = new javax.swing.JCheckBox();
        chkAbdominais = new javax.swing.JCheckBox();
        chkNatacao = new javax.swing.JCheckBox();
        chkDefesaPessoal = new javax.swing.JCheckBox();
        chkRastejarLama = new javax.swing.JCheckBox();
        chkPraticaTiro = new javax.swing.JCheckBox();
        lbAtividadesRealizadas = new javax.swing.JLabel();
        btSalvarAtividade = new javax.swing.JButton();
        btBuscarSoldadoAtividade = new javax.swing.JButton();
        btNumeroAdvertencias = new javax.swing.JButton();
        tfNumeroAdvertencias = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Atividades");

        panelAtividade.setBackground(new java.awt.Color(0, 102, 51));

        lbIconAtividade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/grenade.png"))); // NOI18N

        lbDutyCallsAtividade.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        lbDutyCallsAtividade.setForeground(new java.awt.Color(255, 255, 0));
        lbDutyCallsAtividade.setText("Duty Calls");

        btVoltarAtividade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btVoltarAtividade.setText("Voltar");
        btVoltarAtividade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltarAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarAtividadeActionPerformed(evt);
            }
        });

        lbCodigoSoldadoAtividade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCodigoSoldadoAtividade.setForeground(new java.awt.Color(255, 255, 255));
        lbCodigoSoldadoAtividade.setText("CÓDIGO DO SOLDADO :");

        lbNomeSoldadoAtividade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNomeSoldadoAtividade.setForeground(new java.awt.Color(255, 255, 255));
        lbNomeSoldadoAtividade.setText("NOME DO SOLDADO :");

        lbCasernaSoldadoAtividade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCasernaSoldadoAtividade.setForeground(new java.awt.Color(255, 255, 255));
        lbCasernaSoldadoAtividade.setText("CASERNA DO SOLDADO :");

        lbCodigoAtividade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCodigoAtividade.setForeground(new java.awt.Color(255, 255, 255));
        lbCodigoAtividade.setText("CÓDIGO DA ATIVIDADE :");

        lbMes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMes.setForeground(new java.awt.Color(255, 255, 255));
        lbMes.setText("MÊS: ");

        try {
            ftfCodigoSoldadoAtividade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCodigoSoldadoAtividade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        tfNomeSoldadoAtividade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        tfCasernaSoldadoAtividade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        try {
            ftfCodigoAtividade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCodigoAtividade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        cbMes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        cbMes.setSelectedIndex(-1);

        chkAulasTeoricas.setBackground(new java.awt.Color(0, 102, 51));
        chkAulasTeoricas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkAulasTeoricas.setForeground(new java.awt.Color(255, 255, 255));
        chkAulasTeoricas.setText("AULAS TEÓRICAS");

        chkCorrida.setBackground(new java.awt.Color(0, 102, 51));
        chkCorrida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkCorrida.setForeground(new java.awt.Color(255, 255, 255));
        chkCorrida.setText("CORRIDA");

        chkFlexoes.setBackground(new java.awt.Color(0, 102, 51));
        chkFlexoes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkFlexoes.setForeground(new java.awt.Color(255, 255, 255));
        chkFlexoes.setText("FLEXÕES");

        chkAbdominais.setBackground(new java.awt.Color(0, 102, 51));
        chkAbdominais.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkAbdominais.setForeground(new java.awt.Color(255, 255, 255));
        chkAbdominais.setText("ABDOMINAIS");

        chkNatacao.setBackground(new java.awt.Color(0, 102, 51));
        chkNatacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkNatacao.setForeground(new java.awt.Color(255, 255, 255));
        chkNatacao.setText("NATAÇÃO");

        chkDefesaPessoal.setBackground(new java.awt.Color(0, 102, 51));
        chkDefesaPessoal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkDefesaPessoal.setForeground(new java.awt.Color(255, 255, 255));
        chkDefesaPessoal.setText("DEFESA PESSOAL");

        chkRastejarLama.setBackground(new java.awt.Color(0, 102, 51));
        chkRastejarLama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkRastejarLama.setForeground(new java.awt.Color(255, 255, 255));
        chkRastejarLama.setText("RASTEJAR NA LAMA");

        chkPraticaTiro.setBackground(new java.awt.Color(0, 102, 51));
        chkPraticaTiro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkPraticaTiro.setForeground(new java.awt.Color(255, 255, 255));
        chkPraticaTiro.setText("PRÁTICA DE TIRO");

        lbAtividadesRealizadas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAtividadesRealizadas.setForeground(new java.awt.Color(255, 255, 255));
        lbAtividadesRealizadas.setText("ATIVIDADES REALIZADAS :");

        btSalvarAtividade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btSalvarAtividade.setText("Salvar Atividade");
        btSalvarAtividade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvarAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarAtividadeActionPerformed(evt);
            }
        });

        btBuscarSoldadoAtividade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btBuscarSoldadoAtividade.setText("Buscar Soldado");
        btBuscarSoldadoAtividade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btBuscarSoldadoAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarSoldadoAtividadeActionPerformed(evt);
            }
        });

        btNumeroAdvertencias.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btNumeroAdvertencias.setText("Nº Advertências");
        btNumeroAdvertencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btNumeroAdvertencias.setEnabled(false);
        btNumeroAdvertencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumeroAdvertenciasActionPerformed(evt);
            }
        });

        tfNumeroAdvertencias.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout panelAtividadeLayout = new javax.swing.GroupLayout(panelAtividade);
        panelAtividade.setLayout(panelAtividadeLayout);
        panelAtividadeLayout.setHorizontalGroup(
            panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtividadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAtividadeLayout.createSequentialGroup()
                        .addGroup(panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAtividadeLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkAulasTeoricas)
                                    .addComponent(chkCorrida)
                                    .addComponent(lbAtividadesRealizadas))
                                .addGap(18, 18, 18)
                                .addGroup(panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkDefesaPessoal)
                                    .addComponent(chkFlexoes))
                                .addGap(18, 18, 18)
                                .addGroup(panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkAbdominais)
                                    .addComponent(chkRastejarLama))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtividadeLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbCodigoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftfCodigoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addGroup(panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAtividadeLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkPraticaTiro)
                                    .addComponent(chkNatacao)))
                            .addGroup(panelAtividadeLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(lbMes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(149, 149, 149))
                    .addGroup(panelAtividadeLayout.createSequentialGroup()
                        .addGroup(panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAtividadeLayout.createSequentialGroup()
                                .addComponent(lbIconAtividade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCodigoSoldadoAtividade)
                                    .addComponent(lbNomeSoldadoAtividade, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(panelAtividadeLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelAtividadeLayout.createSequentialGroup()
                                        .addComponent(btSalvarAtividade)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(panelAtividadeLayout.createSequentialGroup()
                                        .addComponent(lbDutyCallsAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbCasernaSoldadoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAtividadeLayout.createSequentialGroup()
                                .addComponent(ftfCodigoSoldadoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(btBuscarSoldadoAtividade))
                            .addComponent(tfNomeSoldadoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAtividadeLayout.createSequentialGroup()
                                .addComponent(tfCasernaSoldadoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btNumeroAdvertencias)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNumeroAdvertencias, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(112, 112, 112))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtividadeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVoltarAtividade)
                .addGap(27, 27, 27))
        );
        panelAtividadeLayout.setVerticalGroup(
            panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtividadeLayout.createSequentialGroup()
                .addGroup(panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelAtividadeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbIconAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAtividadeLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCodigoSoldadoAtividade)
                            .addComponent(ftfCodigoSoldadoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btBuscarSoldadoAtividade))
                        .addGap(26, 26, 26)
                        .addGroup(panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNomeSoldadoAtividade)
                            .addComponent(tfNomeSoldadoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDutyCallsAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCasernaSoldadoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btNumeroAdvertencias)
                        .addComponent(tfNumeroAdvertencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbCasernaSoldadoAtividade))
                .addGap(37, 37, 37)
                .addGroup(panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoAtividade)
                    .addComponent(ftfCodigoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMes)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(lbAtividadesRealizadas)
                .addGap(18, 18, 18)
                .addGroup(panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAulasTeoricas)
                    .addComponent(chkFlexoes)
                    .addComponent(chkAbdominais)
                    .addComponent(chkNatacao))
                .addGap(27, 27, 27)
                .addGroup(panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCorrida)
                    .addComponent(chkDefesaPessoal)
                    .addComponent(chkRastejarLama)
                    .addComponent(chkPraticaTiro))
                .addGap(39, 39, 39)
                .addGroup(panelAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVoltarAtividade)
                    .addComponent(btSalvarAtividade))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAtividade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAtividade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarAtividadeActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarAtividadeActionPerformed

    private void btSalvarAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarAtividadeActionPerformed
        Atividade atividade = new Atividade();
        
        atividade.setCodigo(Integer.parseInt(ftfCodigoAtividade.getText()));
        atividade.setMes(cbMes.getSelectedItem().toString());
        atividade.setAulasTeoricas(chkAulasTeoricas.isSelected());
        atividade.setFlexoes(chkFlexoes.isSelected());
        atividade.setAbdominais(chkAbdominais.isSelected());
        atividade.setNatacao(chkNatacao.isSelected());
        atividade.setCorrida(chkCorrida.isSelected());
        atividade.setDefesaPessoal(chkDefesaPessoal.isSelected());
        atividade.setRastejarLama(chkRastejarLama.isSelected());
        atividade.setPraticaTiro(chkPraticaTiro.isSelected());
        atividade.setCodigoSoldado(Integer.parseInt(ftfCodigoSoldadoAtividade.getText()));
        atividade.setNomeSoldado(tfNomeSoldadoAtividade.getText());
        
        try {
            GravaAtividade.cadastrarNovaAtividade(atividade);
        } catch (SQLException ex) {
            Logger.getLogger(FrameAtividade.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(chkAulasTeoricas.isSelected() == true &&
           chkFlexoes.isSelected() == true &&
           chkAbdominais.isSelected() == true &&
           chkNatacao.isSelected() == true &&
           chkCorrida.isSelected() == true &&
           chkDefesaPessoal.isSelected() == true &&
           chkRastejarLama.isSelected() == true &&
           chkPraticaTiro.isSelected() == true) {
                dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Atividade Mensal Incompleta!", "ADVERTÊNCIA", JOptionPane.WARNING_MESSAGE);
            String codigoSoldado;
            int adv;
            codigoSoldado = ftfCodigoSoldadoAtividade.getText();
            adv = Integer.parseInt(tfNumeroAdvertencias.getText());
            adv = adv + 1;
            try {
                GravaAtividade.contarAdvertencia(codigoSoldado, adv);
            } catch (SQLException ex) {
                Logger.getLogger(FrameAtividade.class.getName()).log(Level.SEVERE, null, ex);
            }
            dispose();
        }
                
    }//GEN-LAST:event_btSalvarAtividadeActionPerformed

    private void btBuscarSoldadoAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarSoldadoAtividadeActionPerformed
        String codigoSoldado;
        ResultSet rs = null;
        
        codigoSoldado = ftfCodigoSoldadoAtividade.getText();
        
        try {
            rs = BuscaAtividade.localizarSoldado(codigoSoldado);
        } catch (SQLException ex) {
            Logger.getLogger(FrameAtividade.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {    
            while(rs.next()) {
                tfNomeSoldadoAtividade.setText(rs.getString("nome"));
                tfCasernaSoldadoAtividade.setText(rs.getString("caserna"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrameAtividade.class.getName()).log(Level.SEVERE, null, ex);
        }
        ftfCodigoSoldadoAtividade.setEditable(false);
        tfNomeSoldadoAtividade.setEditable(false);
        tfCasernaSoldadoAtividade.setEditable(false);
        btNumeroAdvertencias.setEnabled(true);
    }//GEN-LAST:event_btBuscarSoldadoAtividadeActionPerformed

    private void btNumeroAdvertenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumeroAdvertenciasActionPerformed
        String codigoSoldado;
        ResultSet rs = null;
        
        codigoSoldado = ftfCodigoSoldadoAtividade.getText();
        
        try {
            rs = BuscaAtividade.localizarAdvertencias(codigoSoldado);
        } catch (SQLException ex) {
            Logger.getLogger(FrameAtividade.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            while(rs.next()) {
                tfNumeroAdvertencias.setText(rs.getString("total"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrameAtividade.class.getName()).log(Level.SEVERE, null, ex);
        }
        tfNumeroAdvertencias.setEditable(false);
    }//GEN-LAST:event_btNumeroAdvertenciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAtividade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarSoldadoAtividade;
    private javax.swing.JButton btNumeroAdvertencias;
    private javax.swing.JButton btSalvarAtividade;
    private javax.swing.JButton btVoltarAtividade;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JCheckBox chkAbdominais;
    private javax.swing.JCheckBox chkAulasTeoricas;
    private javax.swing.JCheckBox chkCorrida;
    private javax.swing.JCheckBox chkDefesaPessoal;
    private javax.swing.JCheckBox chkFlexoes;
    private javax.swing.JCheckBox chkNatacao;
    private javax.swing.JCheckBox chkPraticaTiro;
    private javax.swing.JCheckBox chkRastejarLama;
    private javax.swing.JFormattedTextField ftfCodigoAtividade;
    private javax.swing.JFormattedTextField ftfCodigoSoldadoAtividade;
    private javax.swing.JLabel lbAtividadesRealizadas;
    private javax.swing.JLabel lbCasernaSoldadoAtividade;
    private javax.swing.JLabel lbCodigoAtividade;
    private javax.swing.JLabel lbCodigoSoldadoAtividade;
    private javax.swing.JLabel lbDutyCallsAtividade;
    private javax.swing.JLabel lbIconAtividade;
    private javax.swing.JLabel lbMes;
    private javax.swing.JLabel lbNomeSoldadoAtividade;
    private javax.swing.JPanel panelAtividade;
    private javax.swing.JTextField tfCasernaSoldadoAtividade;
    private javax.swing.JTextField tfNomeSoldadoAtividade;
    private javax.swing.JTextField tfNumeroAdvertencias;
    // End of variables declaration//GEN-END:variables
}
