
package view;

import controller.BuscaAdvertencia;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTextArea;

/**
 * Frame para a criação de uma janela com informações sobre advertências dos soldados.
 * @author Guilherme Souto Cardoso
 * @since Classe criada em: 06/11/2017
 */

public class FrameAdvertencia extends javax.swing.JFrame {

    /**
     * Creates new form FrameAdvertencia
     */
    public FrameAdvertencia() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAdvertencia = new javax.swing.JPanel();
        lbTituloAdvertencia = new javax.swing.JLabel();
        lbCodigoSoldado = new javax.swing.JLabel();
        lbNomeSoldado = new javax.swing.JLabel();
        ftfCodigoSoldado = new javax.swing.JFormattedTextField();
        btBuscarSoldado = new javax.swing.JButton();
        tfNomeSoldado = new javax.swing.JTextField();
        lbQuantidadeAdvertencias = new javax.swing.JLabel();
        tfQuantidadeAdvertencias = new javax.swing.JTextField();
        btVerificarSituacao = new javax.swing.JButton();
        tfSituacao = new javax.swing.JTextField();
        btDetalhes = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Advertências e situação dos soldados");

        panelAdvertencia.setBackground(new java.awt.Color(0, 102, 51));

        lbTituloAdvertencia.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbTituloAdvertencia.setForeground(new java.awt.Color(255, 255, 255));
        lbTituloAdvertencia.setText("Advertências do Soldado");

        lbCodigoSoldado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCodigoSoldado.setForeground(new java.awt.Color(255, 255, 255));
        lbCodigoSoldado.setText("CÓDIGO SOLDADO :");

        lbNomeSoldado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNomeSoldado.setForeground(new java.awt.Color(255, 255, 255));
        lbNomeSoldado.setText("NOME DO SOLDADO");

        try {
            ftfCodigoSoldado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCodigoSoldado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btBuscarSoldado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btBuscarSoldado.setText("Buscar Soldado");
        btBuscarSoldado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btBuscarSoldado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarSoldadoActionPerformed(evt);
            }
        });

        tfNomeSoldado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lbQuantidadeAdvertencias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbQuantidadeAdvertencias.setForeground(new java.awt.Color(255, 255, 255));
        lbQuantidadeAdvertencias.setText("QUANTIDADE DE ADVERTÊNCIAS = ");

        tfQuantidadeAdvertencias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfQuantidadeAdvertencias.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btVerificarSituacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btVerificarSituacao.setText("Verificar Situação");
        btVerificarSituacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVerificarSituacao.setEnabled(false);
        btVerificarSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerificarSituacaoActionPerformed(evt);
            }
        });

        tfSituacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btDetalhes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btDetalhes.setText("Detalhes...");
        btDetalhes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDetalhes.setEnabled(false);
        btDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDetalhesActionPerformed(evt);
            }
        });

        btVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAdvertenciaLayout = new javax.swing.GroupLayout(panelAdvertencia);
        panelAdvertencia.setLayout(panelAdvertenciaLayout);
        panelAdvertenciaLayout.setHorizontalGroup(
            panelAdvertenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdvertenciaLayout.createSequentialGroup()
                .addGroup(panelAdvertenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdvertenciaLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(lbCodigoSoldado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ftfCodigoSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAdvertenciaLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btBuscarSoldado))
                    .addGroup(panelAdvertenciaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panelAdvertenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelAdvertenciaLayout.createSequentialGroup()
                                .addComponent(btVerificarSituacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btDetalhes))
                            .addComponent(lbNomeSoldado)
                            .addComponent(lbTituloAdvertencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfNomeSoldado)
                            .addGroup(panelAdvertenciaLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(lbQuantidadeAdvertencias)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfQuantidadeAdvertencias, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdvertenciaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btVoltar)
                .addGap(200, 200, 200))
        );
        panelAdvertenciaLayout.setVerticalGroup(
            panelAdvertenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdvertenciaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbTituloAdvertencia)
                .addGap(48, 48, 48)
                .addGroup(panelAdvertenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoSoldado)
                    .addComponent(ftfCodigoSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btBuscarSoldado)
                .addGap(35, 35, 35)
                .addComponent(lbNomeSoldado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNomeSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelAdvertenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuantidadeAdvertencias)
                    .addComponent(tfQuantidadeAdvertencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panelAdvertenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVerificarSituacao)
                    .addComponent(tfSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDetalhes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btVoltar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAdvertencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAdvertencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVerificarSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerificarSituacaoActionPerformed
        String qtde = tfQuantidadeAdvertencias.getText();
        
        if(qtde.equals("0") || qtde.equals("1")) {
            tfSituacao.setText("Nenhuma Punição");
            tfSituacao.setForeground(Color.GRAY);    
        } if(qtde.equals("2") || qtde.equals("3")) {
            tfSituacao.setText("Punição Leve");
            tfSituacao.setForeground(Color.MAGENTA);
            btDetalhes.setEnabled(true);
        } if(qtde.equals("4") || qtde.equals("5")) {
            tfSituacao.setText("Punição Média");
            tfSituacao.setForeground(Color.BLUE);
            btDetalhes.setEnabled(true);
        } if(qtde.equals("6") || qtde.equals("7")) {
            tfSituacao.setText("Punição Pesada");
            tfSituacao.setForeground(Color.ORANGE);
            btDetalhes.setEnabled(true);
        } if(qtde.equals("8")) {
            tfSituacao.setText("Expulsão!");
            tfSituacao.setForeground(Color.RED);
        }
            
    }//GEN-LAST:event_btVerificarSituacaoActionPerformed

    private void btBuscarSoldadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarSoldadoActionPerformed
        String codigoSoldado;
        ResultSet rs = null;
        
        codigoSoldado = ftfCodigoSoldado.getText();
        
        try {
            rs = BuscaAdvertencia.localizarAdvertenciasSoldado(codigoSoldado);
        } catch (SQLException ex) {
            Logger.getLogger(FrameAdvertencia.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            while(rs.next()) {
                tfNomeSoldado.setText(rs.getString("nomesoldado"));
                tfQuantidadeAdvertencias.setText(rs.getString("total"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrameAdvertencia.class.getName()).log(Level.SEVERE, null, ex);
        }
        btVerificarSituacao.setEnabled(true);
        ftfCodigoSoldado.setEditable(false);
        tfNomeSoldado.setEditable(false);
    }//GEN-LAST:event_btBuscarSoldadoActionPerformed

    private void btDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDetalhesActionPerformed
        String qtde = tfQuantidadeAdvertencias.getText();
        JFrame frame = new JFrame();
        JTextArea jta = new JTextArea();
        String info;
        
        if(qtde.equals("2") || qtde.equals("3")) {
            frame.setVisible(true);
            frame.setTitle("Punição Leve");
            frame.setSize(350, 400);
            frame.setLocation(935, 240);
            frame.setResizable(false);
            frame.add(jta);
            jta.setEditable(false);
            info = "\n    Punição Leve \n\n\n\n    - Pagar 30 flexões e 30 abdominais"
                    + "\n\n    - Banhos de 2 minutos por uma semana"
                    + "\n\n    - Menos 10 minutos para as refeições por uma semana";
            jta.setText(info);
        } if(qtde.equals("4") || qtde.equals("5")) {
            frame.setVisible(true);
            frame.setTitle("Punição Média");
            frame.setSize(350, 400);
            frame.setLocation(935, 240);
            frame.setResizable(false);
            frame.add(jta);
            jta.setEditable(false);
            info = "\n    Punição Média \n\n\n\n    - Pagar 60 flexões e 60 abdominais"
                    + "\n\n    - Banhos de 2 minutos por duas semanas"
                    + "\n\n    - Menos 15 minutos para as refeições por duas semanas";
            jta.setText(info);
        } if(qtde.equals("6") || qtde.equals("7")) {
            frame.setVisible(true);
            frame.setTitle("Punição Pesada");
            frame.setSize(350, 400);
            frame.setLocation(935, 240);
            frame.setResizable(false);
            frame.add(jta);
            jta.setEditable(false);
            info = "\n    Punição Pesada \n\n\n\n    - Pagar 90 flexões e 90 abdominais"
                    + "\n\n    - Banhos de 2 minutos por três semanas"
                    + "\n\n    - Menos 20 minutos para as refeições por três semana"
                    + "\n\n    - Lavar as fardas dos soldados da Infantaria";
            jta.setText(info);
        }
    }//GEN-LAST:event_btDetalhesActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAdvertencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAdvertencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAdvertencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAdvertencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAdvertencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarSoldado;
    private javax.swing.JButton btDetalhes;
    private javax.swing.JButton btVerificarSituacao;
    private javax.swing.JButton btVoltar;
    private javax.swing.JFormattedTextField ftfCodigoSoldado;
    private javax.swing.JLabel lbCodigoSoldado;
    private javax.swing.JLabel lbNomeSoldado;
    private javax.swing.JLabel lbQuantidadeAdvertencias;
    private javax.swing.JLabel lbTituloAdvertencia;
    private javax.swing.JPanel panelAdvertencia;
    private javax.swing.JTextField tfNomeSoldado;
    private javax.swing.JTextField tfQuantidadeAdvertencias;
    private javax.swing.JTextField tfSituacao;
    // End of variables declaration//GEN-END:variables
}
